### PR TITLE
Week-9

### PR DESCRIPTION
**Pull request by KJeiii**
1. 姓名：張凱捷
2. 可測試網址：
http://3.106.20.120:3000/api/attractions?page=1
http://3.106.20.120:3000/api/attractions?page=0&keyword=劍潭
http://3.106.20.120:3000/api/attractions?page=0&keyword=北
http://3.106.20.120:3000/api/attraction/10
http://3.106.20.120:3000/api/mrts

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. http://3.106.20.120:3000/api/attractions?page=0&keyword=%E5%8C%97 should contain 12 attractions. http://3.106.20.120:3000/api/attractions?page=2&keyword=%E5%8C%97 should have no data because there are only 15 attractions which makes only 2 pages after filtering by `北`.
2. `img` field should be `images`.
3. Don't use id to do pagination because id is primary key which only promise unique, not continuous.

Fix issues and re-request review.

**Comment by KJeiii** [comment]
Problems below were fixed:
1. attractions api : 
   a. firstly, filtered by keyword 
   b. secondly, pagination by 12 per page

2. replace img with images

@cwpeng

**Review by cwpeng — CHANGES_REQUESTED** [review]
We never get all data from database at once and paging by our own code. We should use SQL query to do pagination directly.

Fix this issue and re-request review.

**Comment by KJeiii** [comment]
Pagination issue fixed : use SQL statement to paging.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
